import { DashboardResponse } from '../models/solicitud.model';
import { CartaAprovisionamiento } from '../../carta-aprovisionamiento/models/carta-aprovisionamiento.model';

const CARTA_SOL_007: CartaAprovisionamiento = {
  areaRequirente: {
    sector:      'Cultural',
    dependencia: 'Secretaría de Cultura',
    responsable: 'L. Méndez',
    cargo:       'Jefe de TI',
    telefono:    '662-555-0143',
    correo:      'l.mendez@cultura.son.gob.mx',
  },
  adminServidor: {
    sector:      'Tecnología',
    dependencia: 'SoftSon S.A.',
    proveedor:   'SoftSon S.A.',
    responsable: 'R. Torres',
    cargo:       'DevOps Lead',
    telefono:    '662-555-0200',
    correo:      'r.torres@softson.mx',
  },
  descripcion: {
    descripcionServidor:       'Servidor para portal de difusión cultural y eventos del estado',
    nombreServidor:            'srv-cultura-app-07',
    nombreAplicacion:          'Portal Cultura Sonora',
    tipoUso:                   'publicado',
    fechaArranque:             '2025-04-01',
    vigencia:                  '12 meses',
    caracteristicasEspeciales: '',
  },
  specs: {
    tipoRequerimiento:    'estandar',
    modalidad:            'nuevo',
    sistemaOperativo:     'linux',
    sistemaOperativoOtro: '',
    vCores:               2,
    memoriaRam:           4,
    discosDuros:          [{ capacidad: 50, tipo: 'SSD', etiqueta: 'Sistema' }],
    motorBD:              'PostgreSQL',
    puertos:              '80, 443, 8080',
    integraciones:        '',
    otrasSpecs:           '',
    ipActual:             '',
    nombreServidorActual: '',
    tipoRenovacion:       '',
  },
  infraestructura: {
    subdominios: [{ subdominio: 'cultura.sonora.gob.mx', puerto: '443' }],
    requiereSSL: true,
    vpns:        [],
  },
  responsiva: {
    firmante:       'L. Méndez',
    numEmpleado:    'EMP-1042',
    puestoFirmante: 'Jefe de TI',
    aceptaTerminos: true,
  },
};

export const DASHBOARD_MOCK: DashboardResponse = {
  metricas: {
    total: 6,
    enProgreso: 3,
    pendientes: 2,
    completadas: 1
  },
  solicitudes: [
    {
      id: 'sol-001',
      folio: 'INF-2025-001',
      dependencia: 'Secretaría de Hacienda',
      nombreServidor: 'srv-hacienda-prod-01',
      estado: 'en_configuracion',
      etapaActual: 5,
      fechaRegistro: '2025-02-10',
      fechaActualizacion: '2025-03-14',
      etapas: [
        { numero: 1,  nombre: 'Registro carta',      estado: 'completada',          fechaActualizacion: '2025-02-10', responsable: 'Juan Pérez' },
        { numero: 2,  nombre: 'Validación recursos', estado: 'completada',          fechaActualizacion: '2025-02-12', responsable: 'Ana López' },
        { numero: 3,  nombre: 'Creación servidor',   estado: 'completada',          fechaActualizacion: '2025-02-18', responsable: 'Carlos Ruiz' },
        { numero: 4,  nombre: 'Comunicaciones',      estado: 'completada',          fechaActualizacion: '2025-02-25', responsable: 'Laura Díaz' },
        { numero: 5,  nombre: 'Parches',              estado: 'en-curso',            fechaActualizacion: '2025-03-14', responsable: 'Luis Mora' },
        { numero: 6,  nombre: 'XDR y agente',         estado: 'sin-iniciar' },
        { numero: 7,  nombre: 'VPN',                  estado: 'sin-iniciar' },
        { numero: 8,  nombre: 'Subdominio',           estado: 'sin-iniciar' },
        { numero: 9,  nombre: 'Credenciales',         estado: 'sin-iniciar' },
        { numero: 10, nombre: 'WAF',                  estado: 'sin-iniciar' },
        { numero: 11, nombre: 'Evidencias',           estado: 'sin-iniciar' },
        { numero: 12, nombre: 'Val. evidencias',      estado: 'sin-iniciar' },
        { numero: 13, nombre: 'Sol. publicación',     estado: 'sin-iniciar' },
        { numero: 14, nombre: 'Vulnerabilidades',     estado: 'sin-iniciar' }
      ]
    },
    {
      id: 'sol-002',
      folio: 'INF-2025-002',
      dependencia: 'Secretaría de Educación',
      nombreServidor: 'srv-educacion-web-02',
      estado: 'pendiente',
      etapaActual: 8,
      fechaRegistro: '2025-01-20',
      fechaActualizacion: '2025-03-10',
      etapas: [
        { numero: 1,  nombre: 'Registro carta',      estado: 'completada' },
        { numero: 2,  nombre: 'Validación recursos', estado: 'completada' },
        { numero: 3,  nombre: 'Creación servidor',   estado: 'completada' },
        { numero: 4,  nombre: 'Comunicaciones',      estado: 'completada' },
        { numero: 5,  nombre: 'Parches',              estado: 'completada' },
        { numero: 6,  nombre: 'XDR y agente',         estado: 'completada' },
        { numero: 7,  nombre: 'VPN',                  estado: 'completada' },
        { numero: 8,  nombre: 'Subdominio',           estado: 'pendiente-respuesta', fechaActualizacion: '2025-03-10', responsable: 'Mario Vega' },
        { numero: 9,  nombre: 'Credenciales',         estado: 'sin-iniciar' },
        { numero: 10, nombre: 'WAF',                  estado: 'sin-iniciar' },
        { numero: 11, nombre: 'Evidencias',           estado: 'sin-iniciar' },
        { numero: 12, nombre: 'Val. evidencias',      estado: 'sin-iniciar' },
        { numero: 13, nombre: 'Sol. publicación',     estado: 'sin-iniciar' },
        { numero: 14, nombre: 'Vulnerabilidades',     estado: 'sin-iniciar' }
      ]
    },
    {
      id: 'sol-003',
      folio: 'INF-2025-003',
      dependencia: 'IMSS',
      nombreServidor: 'srv-imss-db-03',
      estado: 'finalizado',
      etapaActual: 14,
      fechaRegistro: '2024-11-05',
      fechaActualizacion: '2025-02-28',
      etapas: [
        { numero: 1,  nombre: 'Registro carta',      estado: 'completada' },
        { numero: 2,  nombre: 'Validación recursos', estado: 'completada' },
        { numero: 3,  nombre: 'Creación servidor',   estado: 'completada' },
        { numero: 4,  nombre: 'Comunicaciones',      estado: 'completada' },
        { numero: 5,  nombre: 'Parches',              estado: 'completada' },
        { numero: 6,  nombre: 'XDR y agente',         estado: 'completada' },
        { numero: 7,  nombre: 'VPN',                  estado: 'completada' },
        { numero: 8,  nombre: 'Subdominio',           estado: 'completada' },
        { numero: 9,  nombre: 'Credenciales',         estado: 'completada' },
        { numero: 10, nombre: 'WAF',                  estado: 'completada' },
        { numero: 11, nombre: 'Evidencias',           estado: 'completada' },
        { numero: 12, nombre: 'Val. evidencias',      estado: 'completada' },
        { numero: 13, nombre: 'Sol. publicación',     estado: 'completada' },
        { numero: 14, nombre: 'Vulnerabilidades',     estado: 'completada' }
      ]
    },
    {
      id: 'sol-004',
      folio: 'INF-2025-004',
      dependencia: 'Secretaría de Salud',
      nombreServidor: 'srv-salud-app-04',
      estado: 'aprovisionado',
      etapaActual: 3,
      fechaRegistro: '2025-03-01',
      fechaActualizacion: '2025-03-13',
      etapas: [
        { numero: 1,  nombre: 'Registro carta',      estado: 'completada' },
        { numero: 2,  nombre: 'Validación recursos', estado: 'completada' },
        { numero: 3,  nombre: 'Creación servidor',   estado: 'en-curso',            fechaActualizacion: '2025-03-13', responsable: 'Pedro Sosa' },
        { numero: 4,  nombre: 'Comunicaciones',      estado: 'sin-iniciar' },
        { numero: 5,  nombre: 'Parches',              estado: 'sin-iniciar' },
        { numero: 6,  nombre: 'XDR y agente',         estado: 'sin-iniciar' },
        { numero: 7,  nombre: 'VPN',                  estado: 'sin-iniciar' },
        { numero: 8,  nombre: 'Subdominio',           estado: 'sin-iniciar' },
        { numero: 9,  nombre: 'Credenciales',         estado: 'sin-iniciar' },
        { numero: 10, nombre: 'WAF',                  estado: 'sin-iniciar' },
        { numero: 11, nombre: 'Evidencias',           estado: 'sin-iniciar' },
        { numero: 12, nombre: 'Val. evidencias',      estado: 'sin-iniciar' },
        { numero: 13, nombre: 'Sol. publicación',     estado: 'sin-iniciar' },
        { numero: 14, nombre: 'Vulnerabilidades',     estado: 'sin-iniciar' }
      ]
    },
    {
      id: 'sol-005',
      folio: 'INF-2025-005',
      dependencia: 'Secretaría de Seguridad',
      nombreServidor: 'srv-seguridad-fw-05',
      estado: 'pendiente',
      etapaActual: 11,
      fechaRegistro: '2025-01-08',
      fechaActualizacion: '2025-03-05',
      etapas: [
        { numero: 1,  nombre: 'Registro carta',      estado: 'completada' },
        { numero: 2,  nombre: 'Validación recursos', estado: 'completada' },
        { numero: 3,  nombre: 'Creación servidor',   estado: 'completada' },
        { numero: 4,  nombre: 'Comunicaciones',      estado: 'completada' },
        { numero: 5,  nombre: 'Parches',              estado: 'completada' },
        { numero: 6,  nombre: 'XDR y agente',         estado: 'completada' },
        { numero: 7,  nombre: 'VPN',                  estado: 'completada' },
        { numero: 8,  nombre: 'Subdominio',           estado: 'completada' },
        { numero: 9,  nombre: 'Credenciales',         estado: 'completada' },
        { numero: 10, nombre: 'WAF',                  estado: 'completada' },
        { numero: 11, nombre: 'Evidencias',           estado: 'pendiente-respuesta', fechaActualizacion: '2025-03-05', responsable: 'Rosa Ibarra' },
        { numero: 12, nombre: 'Val. evidencias',      estado: 'sin-iniciar' },
        { numero: 13, nombre: 'Sol. publicación',     estado: 'sin-iniciar' },
        { numero: 14, nombre: 'Vulnerabilidades',     estado: 'sin-iniciar' }
      ]
    },
    {
      id: 'sol-006',
      folio: 'INF-2025-006',
      dependencia: 'Poder Judicial',
      nombreServidor: 'srv-pjf-int-06',
      estado: 'recursos_asignados',
      etapaActual: 2,
      fechaRegistro: '2025-03-12',
      fechaActualizacion: '2025-03-15',
      etapas: [
        { numero: 1,  nombre: 'Registro carta',      estado: 'completada' },
        { numero: 2,  nombre: 'Validación recursos', estado: 'en-curso',            fechaActualizacion: '2025-03-15', responsable: 'Ana López' },
        { numero: 3,  nombre: 'Creación servidor',   estado: 'sin-iniciar' },
        { numero: 4,  nombre: 'Comunicaciones',      estado: 'sin-iniciar' },
        { numero: 5,  nombre: 'Parches',              estado: 'sin-iniciar' },
        { numero: 6,  nombre: 'XDR y agente',         estado: 'sin-iniciar' },
        { numero: 7,  nombre: 'VPN',                  estado: 'sin-iniciar' },
        { numero: 8,  nombre: 'Subdominio',           estado: 'sin-iniciar' },
        { numero: 9,  nombre: 'Credenciales',         estado: 'sin-iniciar' },
        { numero: 10, nombre: 'WAF',                  estado: 'sin-iniciar' },
        { numero: 11, nombre: 'Evidencias',           estado: 'sin-iniciar' },
        { numero: 12, nombre: 'Val. evidencias',      estado: 'sin-iniciar' },
        { numero: 13, nombre: 'Sol. publicación',     estado: 'sin-iniciar' },
        { numero: 14, nombre: 'Vulnerabilidades',     estado: 'sin-iniciar' }
      ]
    },
    {
      id: 'sol-007',
      folio: 'INF-2025-007',
      dependencia: 'Secretaría de Cultura',
      nombreServidor: 'srv-cultura-app-07',
      estado: 'pendiente',
      etapaActual: 1,
      fechaRegistro: '2025-03-14',
      fechaActualizacion: '2025-03-15',
      carta: CARTA_SOL_007,
      etapas: [
        { numero: 1,  nombre: 'Registro carta',      estado: 'en-curso',            fechaActualizacion: '2025-03-15', responsable: 'Laura Díaz' },
        { numero: 2,  nombre: 'Validación recursos', estado: 'sin-iniciar' },
        { numero: 3,  nombre: 'Creación servidor',   estado: 'sin-iniciar' },
        { numero: 4,  nombre: 'Comunicaciones',      estado: 'sin-iniciar' },
        { numero: 5,  nombre: 'Parches',              estado: 'sin-iniciar' },
        { numero: 6,  nombre: 'XDR y agente',         estado: 'sin-iniciar' },
        { numero: 7,  nombre: 'VPN',                  estado: 'sin-iniciar' },
        { numero: 8,  nombre: 'Subdominio',           estado: 'sin-iniciar' },
        { numero: 9,  nombre: 'Credenciales',         estado: 'sin-iniciar' },
        { numero: 10, nombre: 'WAF',                  estado: 'sin-iniciar' },
        { numero: 11, nombre: 'Evidencias',           estado: 'sin-iniciar' },
        { numero: 12, nombre: 'Val. evidencias',      estado: 'sin-iniciar' },
        { numero: 13, nombre: 'Sol. publicación',     estado: 'sin-iniciar' },
        { numero: 14, nombre: 'Vulnerabilidades',     estado: 'sin-iniciar' }
      ]

    }

  ]
};
