// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SolicitudServidores.DBContext;

#nullable disable

namespace SolicitudServidores.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260430102813_AddFolioToVpn")]
    partial class AddFolioToVpn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SolicitudServidores.Models.AdminDepContactInformation", b =>
                {
                    b.Property<int>("AdminContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("admin_contact_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdminContactId"));

                    b.Property<string>("AdminServidor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("admin_servidor");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo");

                    b.Property<int>("DependencyId")
                        .HasColumnType("integer")
                        .HasColumnName("dependency_id");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("proveedor");

                    b.HasKey("AdminContactId");

                    b.HasIndex("DependencyId");

                    b.ToTable("admin_dep_contact_information", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Almacenamiento", b =>
                {
                    b.Property<int>("StorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("storage_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StorageId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint")
                        .HasColumnName("server_id");

                    b.Property<int>("StorageCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("storage_capacity");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("StorageId");

                    b.HasIndex("ServerId");

                    b.ToTable("storage", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.AnalisisVulnerabilidades", b =>
                {
                    b.Property<long>("AnalisisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("analisis_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AnalisisId"));

                    b.Property<DateTime?>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analyzed_at");

                    b.Property<long?>("AnalyzedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("analyzed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pendiente")
                        .HasColumnName("estado");

                    b.Property<string>("Hallazgos")
                        .HasColumnType("text")
                        .HasColumnName("hallazgos");

                    b.Property<DateTime?>("PublicadoAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicado_at");

                    b.Property<long?>("PublicadoBy")
                        .HasColumnType("bigint")
                        .HasColumnName("publicado_by");

                    b.Property<string>("Recomendaciones")
                        .HasColumnType("text")
                        .HasColumnName("recomendaciones");

                    b.Property<int>("Ronda")
                        .HasColumnType("integer")
                        .HasColumnName("ronda");

                    b.Property<long>("SolicitudId")
                        .HasColumnType("bigint")
                        .HasColumnName("solicitud_id");

                    b.Property<DateTime?>("SolicitudPublicacionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("solicitud_publicacion_at");

                    b.Property<long?>("SolicitudPublicacionBy")
                        .HasColumnType("bigint")
                        .HasColumnName("solicitud_publicacion_by");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AnalisisId");

                    b.HasIndex("AnalyzedBy");

                    b.HasIndex("PublicadoBy");

                    b.HasIndex("SolicitudPublicacionBy");

                    b.HasIndex("SolicitudId", "Ronda")
                        .IsUnique();

                    b.ToTable("analisis_vulnerabilidades", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Carta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("carta_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("FirmaAtdtAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("firma_atdt_at");

                    b.Property<DateTime?>("FirmaDependenciaAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("firma_dependencia_at");

                    b.Property<string>("FirmanteAtdtNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("firmante_atdt_nombre");

                    b.Property<string>("FirmanteAtdtPuesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firmante_atdt_puesto");

                    b.Property<string>("FirmanteDependenciaEmpleado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("firmante_dependencia_empleado");

                    b.Property<string>("FirmanteDependenciaNombre")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("firmante_dependencia_nombre");

                    b.Property<string>("FirmanteDependenciaPuesto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firmante_dependencia_puesto");

                    b.Property<string>("FolioCarta")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("folio_carta");

                    b.Property<DateTime?>("PdfGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pdf_generated_at");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pdf_path");

                    b.Property<long>("SolicitudId")
                        .HasColumnType("bigint")
                        .HasColumnName("solicitud_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SolicitudId")
                        .IsUnique();

                    b.ToTable("carta", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Dependency", b =>
                {
                    b.Property<int>("DependencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dependency_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DependencyId"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Responsable")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("responsable");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sector");

                    b.HasKey("DependencyId");

                    b.ToTable("dependency", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Evidencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("evidencia_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArchivoNombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("archivo_nombre");

                    b.Property<string>("ArchivoPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("archivo_path");

                    b.Property<int?>("ArchivoSizeKb")
                        .HasColumnType("integer")
                        .HasColumnName("archivo_size_kb");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EstadoValidacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pendiente")
                        .HasColumnName("estado_validacion");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("text")
                        .HasColumnName("motivo_rechazo");

                    b.Property<string>("Proposito")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("proposito");

                    b.Property<int>("Ronda")
                        .HasColumnType("integer")
                        .HasColumnName("ronda");

                    b.Property<long>("SolicitudId")
                        .HasColumnType("bigint")
                        .HasColumnName("solicitud_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<long>("UploadedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_by");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.Property<long?>("ValidatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("validated_by");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("ValidatedBy");

                    b.ToTable("evidencia", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("notification_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean")
                        .HasColumnName("leida");

                    b.Property<DateTime?>("LeidaAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leida_at");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<long>("RecipientUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipient_user_id");

                    b.Property<long?>("SenderUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_user_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("NotificationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("RecipientUserId", "Leida");

                    b.ToTable("notifications", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Roles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("RoleId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Seguimiento", b =>
                {
                    b.Property<long>("SeguimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seguimiento_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SeguimientoId"));

                    b.Property<long?>("CompletadoBy")
                        .HasColumnType("bigint")
                        .HasColumnName("completado_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EtapaNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("etapa_nombre");

                    b.Property<int>("EtapaNumero")
                        .HasColumnType("integer")
                        .HasColumnName("etapa_numero");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_completado");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<long>("SolicitudId")
                        .HasColumnType("bigint")
                        .HasColumnName("solicitud_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pendiente")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SeguimientoId");

                    b.HasIndex("CompletadoBy");

                    b.HasIndex("SolicitudId", "EtapaNumero")
                        .IsUnique();

                    b.ToTable("seguimiento", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.ServerSubdominio", b =>
                {
                    b.Property<int>("ServerSubdominioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("server_subdominio_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServerSubdominioId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint")
                        .HasColumnName("server_id");

                    b.Property<int>("SubdominioId")
                        .HasColumnType("integer")
                        .HasColumnName("subdominio_id");

                    b.HasKey("ServerSubdominioId");

                    b.HasIndex("ServerId");

                    b.HasIndex("SubdominioId", "ServerId")
                        .IsUnique();

                    b.ToTable("server_subdominio", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.ServerVpn", b =>
                {
                    b.Property<int>("ServerVpnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("server_vpn_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServerVpnId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint")
                        .HasColumnName("server_id");

                    b.Property<int>("VpnId")
                        .HasColumnType("integer")
                        .HasColumnName("vpn_id");

                    b.HasKey("ServerVpnId");

                    b.HasIndex("ServerId");

                    b.HasIndex("VpnId", "ServerId")
                        .IsUnique();

                    b.ToTable("server_vpn", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Servidor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Almacenamiento")
                        .HasColumnType("integer")
                        .HasColumnName("almacenamiento");

                    b.Property<bool>("ComunicacionValidada")
                        .HasColumnType("boolean")
                        .HasColumnName("comunicacion_validada");

                    b.Property<bool>("CredencialesEntregadas")
                        .HasColumnType("boolean")
                        .HasColumnName("credenciales_entregadas");

                    b.Property<int>("DependencyId")
                        .HasColumnType("integer")
                        .HasColumnName("dependency_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("Estado");

                    b.Property<string>("EtapaOperativa")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("etapa_operativa");

                    b.Property<string>("EtapaVulnerabilidades")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("etapa_vulnerabilidades");

                    b.Property<bool>("EvidenciaValidada")
                        .HasColumnType("boolean")
                        .HasColumnName("evidencia_validada");

                    b.Property<DateTime?>("Expiracion")
                        .HasColumnType("date")
                        .HasColumnName("expiracion");

                    b.Property<DateTime?>("FechaAsignacionIp")
                        .HasColumnType("date")
                        .HasColumnName("fecha_asignacion_ip");

                    b.Property<DateTime?>("FechaConfiguracionWaf")
                        .HasColumnType("date")
                        .HasColumnName("fecha_configuracion_waf");

                    b.Property<DateTime?>("FechaEntregaCredenciales")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega_credenciales");

                    b.Property<DateTime?>("FechaParches")
                        .HasColumnType("date")
                        .HasColumnName("fecha_parches");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_publicacion");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ultima_actualizacion");

                    b.Property<DateTime?>("FechaValidacionComunicacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_validacion_comunicacion");

                    b.Property<DateTime?>("FechaValidacionEvidencia")
                        .HasColumnType("date")
                        .HasColumnName("fecha_validacion_evidencia");

                    b.Property<DateTime?>("FechaVulnerabilidades")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vulnerabilidades");

                    b.Property<DateTime?>("FechaXdr")
                        .HasColumnType("date")
                        .HasColumnName("fecha_xdr");

                    b.Property<string>("Funcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("funcion");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("hostname");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("LlaveOS")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("llaveOS");

                    b.Property<int>("Nucleos")
                        .HasColumnType("integer")
                        .HasColumnName("nucleos");

                    b.Property<string>("ObservacionesSeguimiento")
                        .HasColumnType("text")
                        .HasColumnName("observaciones_seguimiento");

                    b.Property<bool>("ParchesAplicados")
                        .HasColumnType("boolean")
                        .HasColumnName("parches_aplicados");

                    b.Property<string>("PlantillaRecursos")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("plantilla_recursos");

                    b.Property<int>("Ram")
                        .HasColumnType("integer")
                        .HasColumnName("ram");

                    b.Property<bool>("RequiereLlaveLicencia")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_llave_licencia");

                    b.Property<bool>("RequiereRevisionAnual")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_revision_anual");

                    b.Property<string>("ResponsableInfraestructura")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("responsable_infraestructura");

                    b.Property<string>("SistemaOperativo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("sistemaOperativo");

                    b.Property<bool>("SolicitudPublicacion")
                        .HasColumnType("boolean")
                        .HasColumnName("solicitud_publicacion");

                    b.Property<string>("TareasPendientes")
                        .HasColumnType("text")
                        .HasColumnName("tareas_pendientes");

                    b.Property<string>("TipoUso")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tipo_uso");

                    b.Property<DateTime?>("UltimaRevisionAnual")
                        .HasColumnType("date")
                        .HasColumnName("ultima_revision_anual");

                    b.Property<string>("UsuarioCredenciales")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("usuario_credenciales");

                    b.Property<string>("UsuarioParches")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("usuario_parches");

                    b.Property<string>("UsuarioPublicacion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("usuario_publicacion");

                    b.Property<string>("UsuarioUltimaActualizacion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("usuario_ultima_actualizacion");

                    b.Property<string>("UsuarioValidacionComunicacion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("usuario_validacion_comunicacion");

                    b.Property<string>("UsuarioValidacionEvidencia")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("usuario_validacion_evidencia");

                    b.Property<string>("UsuarioVulnerabilidades")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("usuario_vulnerabilidades");

                    b.Property<string>("UsuarioWaf")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("usuario_waf");

                    b.Property<string>("UsuarioXdr")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("usuario_xdr");

                    b.Property<bool>("WafConfigurado")
                        .HasColumnType("boolean")
                        .HasColumnName("waf_configurado");

                    b.Property<bool>("XdrInstalado")
                        .HasColumnType("boolean")
                        .HasColumnName("xdr_instalado");

                    b.HasKey("Id");

                    b.HasIndex("DependencyId");

                    b.ToTable("servidor", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Solicitud", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("solicitud_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AdminContactId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_contact_id");

                    b.Property<int>("AlmacenamientoSolicitadoGb")
                        .HasColumnType("integer")
                        .HasColumnName("almacenamiento_solicitado_gb");

                    b.Property<string>("CaracteristicasEspeciales")
                        .HasColumnType("text")
                        .HasColumnName("caracteristicas_especiales");

                    b.Property<string>("ConectividadOtras")
                        .HasColumnType("text")
                        .HasColumnName("conectividad_otras");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DependencyId")
                        .HasColumnType("integer")
                        .HasColumnName("dependency_id");

                    b.Property<string>("DescripcionUso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion_uso");

                    b.Property<bool>("EsClonacion")
                        .HasColumnType("boolean")
                        .HasColumnName("es_clonacion");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("pendiente")
                        .HasColumnName("estatus");

                    b.Property<DateTime?>("FechaArranqueDeseada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_arranque_deseada");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("folio");

                    b.Property<string>("IntegracionesExternas")
                        .HasColumnType("text")
                        .HasColumnName("integraciones_externas");

                    b.Property<string>("IpServidorBase")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_servidor_base");

                    b.Property<string>("MotorBaseDatos")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("motor_base_datos");

                    b.Property<string>("NombreAplicacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_aplicacion");

                    b.Property<string>("NombreServidor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_servidor");

                    b.Property<string>("NombreServidorBase")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_servidor_base");

                    b.Property<int>("RamSolicitadaGb")
                        .HasColumnType("integer")
                        .HasColumnName("ram_solicitada_gb");

                    b.Property<string>("ReglasFirewall")
                        .HasColumnType("text")
                        .HasColumnName("reglas_firewall");

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint")
                        .HasColumnName("server_id");

                    b.Property<string>("SistemaOperativo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sistema_operativo");

                    b.Property<string>("TipoRequerimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_requerimiento");

                    b.Property<string>("TipoUso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_uso");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<int>("VcpuSolicitado")
                        .HasColumnType("integer")
                        .HasColumnName("vcpu_solicitado");

                    b.Property<int>("VigenciaMeses")
                        .HasColumnType("integer")
                        .HasColumnName("vigencia_meses");

                    b.HasKey("Id");

                    b.HasIndex("AdminContactId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DependencyId");

                    b.HasIndex("Estatus");

                    b.HasIndex("Folio")
                        .IsUnique();

                    b.HasIndex("ServerId")
                        .IsUnique();

                    b.ToTable("solicitud", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Subdominio", b =>
                {
                    b.Property<int>("SubdominioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("subdominio_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubdominioId"));

                    b.Property<string>("ApprovedName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("approved_name");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int?>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("RequestedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("requested_name");

                    b.Property<bool>("SslRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("ssl_required");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("solicitado")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SubdominioId");

                    b.ToTable("subdominio", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DependencyId")
                        .HasColumnType("integer")
                        .HasColumnName("dependency_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroEmpleado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_empleado");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DependencyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.VPN", b =>
                {
                    b.Property<int>("VpnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vpn_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VpnId"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Empresa")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("empresa");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_id");

                    b.Property<string>("Folio")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("folio");

                    b.Property<string>("PerfilAnterior")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("perfil_anterior");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("responsable");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VigenciaDias")
                        .HasColumnType("integer")
                        .HasColumnName("vigencia_dias");

                    b.Property<string>("VpnIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("vpn_ip");

                    b.Property<string>("VpnType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("vpn_type");

                    b.HasKey("VpnId");

                    b.ToTable("vpn", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.WafConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("waf_config_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Configurado")
                        .HasColumnType("boolean")
                        .HasColumnName("configurado");

                    b.Property<DateTime?>("ConfiguredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("configured_at");

                    b.Property<long?>("ConfiguredBy")
                        .HasColumnType("bigint")
                        .HasColumnName("configured_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("Id_Servidor")
                        .HasColumnType("bigint")
                        .HasColumnName("server_id");

                    b.Property<string>("ReglasAplicadas")
                        .HasColumnType("text")
                        .HasColumnName("reglas_aplicadas");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguredBy");

                    b.HasIndex("Id_Servidor")
                        .IsUnique();

                    b.ToTable("waf_config", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.AdminDepContactInformation", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Dependency", "Dependency")
                        .WithMany("AdminContacts")
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependency");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Almacenamiento", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Servidor", "Servidor")
                        .WithMany("Storages")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servidor");
                });

            modelBuilder.Entity("SolicitudServidores.Models.AnalisisVulnerabilidades", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Usuario", "AnalizadoPor")
                        .WithMany()
                        .HasForeignKey("AnalyzedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SolicitudServidores.Models.Usuario", "PublicadoPor")
                        .WithMany()
                        .HasForeignKey("PublicadoBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SolicitudServidores.Models.Solicitud", "Solicitud")
                        .WithMany("AnalisisVulnerabilidades")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolicitudServidores.Models.Usuario", "SolicitadoPor")
                        .WithMany()
                        .HasForeignKey("SolicitudPublicacionBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnalizadoPor");

                    b.Navigation("PublicadoPor");

                    b.Navigation("SolicitadoPor");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Carta", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolicitudServidores.Models.Solicitud", "Solicitud")
                        .WithOne("Carta")
                        .HasForeignKey("SolicitudServidores.Models.Carta", "SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreadoPor");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Evidencia", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Solicitud", "Solicitud")
                        .WithMany("Evidencias")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolicitudServidores.Models.Usuario", "SubidoPor")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolicitudServidores.Models.Usuario", "ValidadoPor")
                        .WithMany()
                        .HasForeignKey("ValidatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Solicitud");

                    b.Navigation("SubidoPor");

                    b.Navigation("ValidadoPor");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Notification", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Usuario", "Destinatario")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolicitudServidores.Models.Usuario", "Remitente")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Destinatario");

                    b.Navigation("Remitente");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Seguimiento", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Usuario", "CompletadoPor")
                        .WithMany()
                        .HasForeignKey("CompletadoBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SolicitudServidores.Models.Solicitud", "Solicitud")
                        .WithMany("Seguimientos")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletadoPor");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("SolicitudServidores.Models.ServerSubdominio", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Servidor", "Servidor")
                        .WithMany("ServerSubdominios")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolicitudServidores.Models.Subdominio", "Subdominio")
                        .WithMany("ServerSubdominios")
                        .HasForeignKey("SubdominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servidor");

                    b.Navigation("Subdominio");
                });

            modelBuilder.Entity("SolicitudServidores.Models.ServerVpn", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Servidor", "Servidor")
                        .WithMany("ServerVpns")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolicitudServidores.Models.VPN", "Vpn")
                        .WithMany("ServerVpns")
                        .HasForeignKey("VpnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servidor");

                    b.Navigation("Vpn");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Servidor", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Dependency", "Dependency")
                        .WithMany("Servidores")
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dependency");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Solicitud", b =>
                {
                    b.HasOne("SolicitudServidores.Models.AdminDepContactInformation", "AdminContact")
                        .WithMany()
                        .HasForeignKey("AdminContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SolicitudServidores.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolicitudServidores.Models.Dependency", "Dependency")
                        .WithMany()
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolicitudServidores.Models.Servidor", "Servidor")
                        .WithOne("Solicitud")
                        .HasForeignKey("SolicitudServidores.Models.Solicitud", "ServerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdminContact");

                    b.Navigation("CreadoPor");

                    b.Navigation("Dependency");

                    b.Navigation("Servidor");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Usuario", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SolicitudServidores.Models.Dependency", "Dependency")
                        .WithMany()
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SolicitudServidores.Models.Roles", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolicitudServidores.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Dependency");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SolicitudServidores.Models.WafConfig", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Usuario", "ConfiguradoPor")
                        .WithMany()
                        .HasForeignKey("ConfiguredBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SolicitudServidores.Models.Servidor", "Servidor")
                        .WithOne("WafConfig")
                        .HasForeignKey("SolicitudServidores.Models.WafConfig", "Id_Servidor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguradoPor");

                    b.Navigation("Servidor");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Dependency", b =>
                {
                    b.Navigation("AdminContacts");

                    b.Navigation("Servidores");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Roles", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Servidor", b =>
                {
                    b.Navigation("ServerSubdominios");

                    b.Navigation("ServerVpns");

                    b.Navigation("Solicitud");

                    b.Navigation("Storages");

                    b.Navigation("WafConfig");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Solicitud", b =>
                {
                    b.Navigation("AnalisisVulnerabilidades");

                    b.Navigation("Carta");

                    b.Navigation("Evidencias");

                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Subdominio", b =>
                {
                    b.Navigation("ServerSubdominios");
                });

            modelBuilder.Entity("SolicitudServidores.Models.VPN", b =>
                {
                    b.Navigation("ServerVpns");
                });
#pragma warning restore 612, 618
        }
    }
}
